#!/bin/sh
clear

do_error=""
wait=""

dumpit() {
    sleep 1
    echo request dump on server
    curl --silent --head http://localhost:3666/dump >/dev/null
}

if [ "$1" = "yes" ]; then
    dumpit &
    wait="--random-wait 2"
    
fi

for sim in A B C D E; do
    if [ $sim = D ]; then
        do_error=--include-errors
    fi

    deno run --allow-net --allow-env src/main.ts $sim $do_error $wait &
done

wait

if [ "$1" = "yes" ]; then
    echo request dump on server
    curl --silent --head http://localhost:3666/dump >/dev/null
fi
echo ALL done
