#!/bin/sh
clear
node src/simulation.js A &
node src/simulation.js B &
node src/simulation.js C &
node src/simulation.js D &
node src/simulation.js E &

sleep 1s
curl --silent --head http://localhost:3666/dump >/dev/null
wait
curl --silent --head http://localhost:3666/dump >/dev/null

echo ALL done
