#!/bin/sh
clear

dumpit() {
    sleep 1
    echo request dump on server
    curl --silent --head http://localhost:3666/dump >/dev/null
}

if [ "$1" = "yes" ]; then
    dumpit &
fi

for sim in A B C D E; do
    deno run --allow-net src/simulation.ts $sim $1 &
done

wait

if [ "$1" = "yes" ]; then
    echo request dump on server
    curl --silent --head http://localhost:3666/dump >/dev/null
fi
echo ALL done
